# show coverage in CI status, not as a comment.
comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90
        threshold: 1%
github_checks:
  annotations: false
