# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_owner: ''
description: Asynchronous Bluesky hardware abstraction code, compatible with control
    systems like EPICS and Tango
distribution_name: ophyd-async
docker: false
docs_type: sphinx
git_platform: github.com
github_org: bluesky
package_name: ophyd_async
pypi: true
repo_name: ophyd-async
type_checker: pyright
