[project]
authors = ["thomashopkins32 <thopkins1@bnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ophyd-async"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pytest = ">=8.3.5,<9"


[pypi-dependencies]
ophyd-async = { path = ".", editable = true }
