from collections.abc import Mapping
from typing import Any

import pytest
from bluesky.protocols import Reading

from ophyd_async.core import AsyncConfigurable, AsyncReadable, SignalDatatypeT, SignalR


def _generate_assert_error_msg(name: str, expected_result, actual_result) -> str:
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    return (
        f"Expected {WARNING}{name}{ENDC} to produce"
        + f"\n{FAIL}{expected_result}{ENDC}"
        + f"\nbut actually got \n{FAIL}{actual_result}{ENDC}"
    )


async def assert_value(signal: SignalR[SignalDatatypeT], value: Any) -> None:
    """Assert that a Signal has the given value.

    Parameters
    ----------
    signal:
        Signal with get_value.
    value:
        The expected value from the signal.
    """
    actual_value = await signal.get_value()
    assert actual_value == value, _generate_assert_error_msg(
        name=signal.name,
        expected_result=value,
        actual_result=actual_value,
    )


def _approx_readable_value(reading: Mapping[str, Reading]) -> Mapping[str, Reading]:
    for i in reading:
        # np_array1 == np_array2 gives an array of booleans rather than a single bool
        # Use pytest.approx(np_array1) so that we get a bool instead
        reading[i]["value"] = pytest.approx(reading[i]["value"])
    return reading


async def assert_reading(
    readable: AsyncReadable,
    reading: Mapping[str, Reading],
) -> None:
    """Assert that a readable Device has the given reading.

    Parameters
    ----------
    readable:
        Device with an async ``read()`` method to get the reading from.
    reading:
        The expected reading from the readable.
    """
    actual_reading = await readable.read()
    assert (
        _approx_readable_value(reading) == actual_reading
    ), _generate_assert_error_msg(
        name=readable.name,
        expected_result=reading,
        actual_result=actual_reading,
    )


async def assert_configuration(
    configurable: AsyncConfigurable,
    configuration: Mapping[str, Reading],
) -> None:
    """Assert that a configurable Device has the given configuration.

    Parameters
    ----------
    configurable:
        Device with an async ``read_configuration()`` method to get the configuration
        from.
    configuration:
        The expected configuration from the configurable.
    """
    actual_configurable = await configurable.read_configuration()
    assert (
        _approx_readable_value(configuration) == actual_configurable
    ), _generate_assert_error_msg(
        name=configurable.name,
        expected_result=configuration,
        actual_result=actual_configurable,
    )


def assert_emitted(docs: Mapping[str, list[dict]], **numbers: int):
    """Assert emitted document generated by running a Bluesky plan

    Parameters
    ----------
    docs:
        A mapping of document type -> list of documents that have been emitted.
    numbers:
        The number of each document type expected.

    Examples
    --------
    .. code::

        docs = defaultdict(list)
        RE.subscribe(lambda name, doc: docs[name].append(doc))
        RE(my_plan())
        assert_emitted(docs, start=1, descriptor=1, event=1, stop=1)
    """
    assert list(docs) == list(numbers), _generate_assert_error_msg(
        name="documents",
        expected_result=list(numbers),
        actual_result=list(docs),
    )
    actual_numbers = {name: len(d) for name, d in docs.items()}
    assert actual_numbers == numbers, _generate_assert_error_msg(
        name="emitted",
        expected_result=numbers,
        actual_result=actual_numbers,
    )
