from functools import partial
from typing import Any

import pytest
from bluesky.protocols import Reading

from ophyd_async.core import (
    AsyncConfigurable,
    AsyncReadable,
    SignalDatatypeT,
    SignalR,
    Table,
)


def _generate_assert_error_msg(name: str, expected_result, actual_result) -> str:
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    return (
        f"Expected {WARNING}{name}{ENDC} to produce"
        + f"\n{FAIL}{expected_result}{ENDC}"
        + f"\nbut actually got \n{FAIL}{actual_result}{ENDC}"
    )


def _value_equal(value1, value2) -> bool:
    return value1 == pytest.approx(value2)


def _table_equal(table1: Table, table2: Table) -> bool:
    # keys and values of all fields should be the same
    if not table1.model_fields == table2.model_fields:
        return False
    for field, value1 in table1:
        if not _value_equal(value1, getattr(table2, field)):
            return False
    return True


async def assert_value(signal: SignalR[SignalDatatypeT], value: Any) -> None:
    """Assert a signal's value and compare it an expected signal.

    Parameters
    ----------
    signal:
        signal with get_value.
    value:
        The expected value from the signal.

    Notes
    -----
    Example usage::
        await assert_value(signal, value)

    """
    actual_value = await signal.get_value()
    error_msg = _generate_assert_error_msg(
        name=signal.name, expected_result=value, actual_result=actual_value
    )
    if isinstance(actual_value, Table):
        assert isinstance(value, Table), error_msg
        assert _table_equal(actual_value, value), error_msg
    else:
        assert _value_equal(value, actual_value), error_msg


async def assert_reading(
    readable: AsyncReadable, expected_reading: dict[str, Reading]
) -> None:
    """Assert readings from readable.

    Parameters
    ----------
    readable:
        Callable with readable.read function that generate readings.

    reading:
        The expected readings from the readable.

    Notes
    -----
    Example usage::
        await assert_reading(readable, reading)

    """
    actual_reading = await readable.read()
    _compare_readings_dicts(actual_reading, expected_reading, readable.name)


async def assert_configuration(
    configurable: AsyncConfigurable,
    configuration: dict[str, Reading],
) -> None:
    """Assert readings from Configurable.

    Parameters
    ----------
    configurable:
        Configurable with Configurable.read function that generate readings.

    configuration:
        The expected readings from configurable.

    Notes
    -----
    Example usage::
        await assert_configuration(configurable configuration)

    """

    actual_configuration = await configurable.read_configuration()
    _compare_readings_dicts(actual_configuration, configuration, configurable.name)


def _compare_metadata(reading1: Reading, reading2: Reading):
    return {k: v for k, v in reading1.items() if k != "value"} == {
        k: v for k, v in reading2.items() if k != "value"
    }


def _compare_readings_dicts(
    actual: dict[str, Reading], expected: dict[str, Reading], name: str
):
    error_msg = partial(
        _generate_assert_error_msg,
        name=name,
        expected_result=expected,
        actual_result=actual,
    )

    assert actual.keys() == expected.keys(), error_msg()
    for key, actual_reading in actual.items():
        if isinstance(actual_reading["value"], Table):
            assert _table_equal(
                actual_reading["value"], expected[key]["value"]
            ) and _compare_metadata(actual_reading, expected[key]), error_msg()
        else:
            expected[key]["value"] = pytest.approx(expected[key]["value"])
            assert actual_reading == expected[key], error_msg()


def assert_emitted(docs: dict[str, list[dict]], **numbers: int):
    """Assert emitted document generated by running a Bluesky plan

    Parameters
    ----------
    Doc:
        A dictionary

    numbers:
        expected emission in kwarg from

    Notes
    -----
    Example usage::
        docs = defaultdict(list)
        RE.subscribe(lambda name, doc: docs[name].append(doc))
        RE(my_plan())
        assert_emitted(docs, start=1, descriptor=1, event=1, stop=1)
    """
    assert list(docs) == list(numbers), _generate_assert_error_msg(
        name="documents",
        expected_result=list(numbers),
        actual_result=list(docs),
    )
    actual_numbers = {name: len(d) for name, d in docs.items()}
    assert actual_numbers == numbers, _generate_assert_error_msg(
        name="emitted",
        expected_result=numbers,
        actual_result=actual_numbers,
    )
