name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        UV_PYTHON="${{ inputs.python-version }}"
        if [ $UV_PYTHON == "dev" ]; then
          UV_PYTHON=$(sed -n "s/ARG UV_PYTHON=//p" Dockerfile)
        fi
        echo "UV_PYTHON=$UV_PYTHON" >> "$GITHUB_ENV"
      shell: bash

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install packages
      run: uv sync
      shell: bash

    - name: Report what was installed
      run: uv tree
      shell: bash
